### ISSUE TITLE
Наименование функций

### ISSUE THREAD

**Issue by Berej** [AbdSayen/ConsoleAdventure#2]
Это не критическая и вообще не ошибка, но я заметил что ты называешь свои функции с заглавной буквы. 
Я тебе советую тебе придерживаться хорошей практике что у Джавистов что и у Шарпистов и именно: Продолжить называть классы также с заглавной, а вот для функций использовать camelCase. Например:

class **Animal** {
    public void **eat()** {
      ...
   }
    ...
}

**Comment by Fess00** [comment]
Про тех, кто пишет на Java не знаю, но на C# сами Microsoft в соглашении о стиле кода приводят следующий тезис: "Используйте PascalCase для имен классов и имен методов.". Так что название методов (так же свойств и т.д.) и классов, по-хорошему нужно писать через PascalCase.
Вот еще ссылка на всё соглашение стиля кода от майков: https://learn.microsoft.com/ru-ru/dotnet/csharp/fundamentals/coding-style/identifier-names.
P.S.: в компаниях (больших и не очень) так же придерживаются такого стиля кода :)
Без негатива, всем добра))

**Comment by AbdSayen** [comment]
Спасибо за предложение! Но я вижу что большинство программистов на C# называют методы с заглавной, так буду делать и я
